services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env #puxando senhas do .env
    depends_on:
      - redis  # Apenas Redis continua sendo necessário
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
