services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # O front-end será acessível no host via http://localhost:3000
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001" # Torna a porta 3001 acessível na rede interna, mas não para o host
    env_file:
      - ./backend/.env #puxando senhas do .env
    depends_on:
      - redis  # Backend depende do Redis
    restart: always

  redis:
    image: redis
    expose:
      - "6379" # Torna a porta 6379 acessível apenas na rede interna
    restart: always
